### ISSUE TITLE
stored proc issue with param bind to PlSqlTable of NUMBER

### ISSUE THREAD

**Issue by crystalgreen** [vrogier/ocilib#225]
My issue is related to #178. I have the similar problems but for me it is still not working.
Tested with OCILIB v4.6.3 and Oracle 12c.

## Problem
_Index by table_ parameters of inner type NUMBER do not seem to work correctly. For VARCHAR2 and DATE it works. 
Bind directions tried: IN/OUT/IN OUT. For IN OUT/ OUT, I don't get any results back. For IN my previously initialized values are still there (as expected).

See also the output of the code below.

# How to reproduce

```sql

void CallPlSqlOutArrayVal(Connection& con)
{
  Statement st(con);
  con.EnableServerOutput(10000, 10, 200);
  st.Prepare((ostring)
    "declare "
    + "type val_tab is table of number index by binary_integer;"
    + "procedure Test( v IN OUT val_tab ) is "
    + "begin "
    + "for i in 1..3 loop "
    + "  DBMS_OUTPUT.PUT_LINE('v('||i||') = '||v(i)); "
    + "  v(i) := i; "
    + "end loop; "
    + "end Test; "
    + "begin "
    + " Test(:v);"
    + " end;");
  int bufferSize = 10;
  st.SetBindArraySize(bufferSize);
  std::vector<Number> valArray(bufferSize);
  for (int i = 0; i < bufferSize; i++) {
    //valArray[i] = Number(true);
    valArray[i] = Number((ostring)std::to_string(i + 1));
  }
  st.Bind(":v", valArray, BindInfo::InOut, BindInfo::VectorTypeValues::AsPlSqlTable);
  st.ExecutePrepared();
  std::string line;
  while (con.GetServerOutput(line))
  {
    std::cout << line << std::endl;
  }
  for (int i = 0; i < bufferSize; i++)
  {
    ostring val = valArray[i].ToString("99");
    std::cout << i << ": " << "VAL:" << val << std::endl;
  }
}

```

Output:

```
v(1) = 1
v(2) = 2
v(3) = 3
0: VAL:
1: VAL:
2: VAL:
3: VAL:
4: VAL:
5: VAL:
6: VAL:
7: VAL:
8: VAL:###
9: VAL:
```

I sometimes get these strange `###` for value outputs, randomly. Maybe some memory overwrite?

**Comment by vrogier** [comment]
Hi,

Thank for report this issue.
I will investigate it using the provided code sample.
I will keep you updated by the end of the weekend ;)

Regards,

Vincent

**Comment by vrogier** [comment]
Hi,

I found the issue and will commit after further tests on the given fix.

Regards,

Vincent

**Comment by vrogier** [comment]
Hi,

About your sample C++ code, you should not call Statement::SetBindArraySize() as documented in the method.
If you remove this call, with the fix committed in the 4.6.4 branch, it works now as expected.

**Comment by crystalgreen** [comment]
Bonjour Vincent,

thanks for the quick reaction. I checked out the branch with your fix, built it and used the new dll in my test project where I removed that SetBindArraySize call. But I still get the same bad results as above. I also have a test that uses the C API and that already worked before. So, I don't see any difference with this fix; I'm pretty sure I used the correct (new) dll.
Your regression test only uses the C API, maybe the issue is in the C++ API?

Btw, I couldn't get your test project to build (cannot open gtest/gtest.h).
PS: I switched the vs2019 project on my clone to platform toolset version v142 as v141_xp is deprecated.

**Comment by vrogier** [comment]
hi,

for the test project, you need the gtest nuget package.
I am going to test the C++ API straight away !

Vincent

**Comment by vrogier** [comment]
I have just re tested and it works with the fix :

Here is the code:

```C++
int main()
{
    ocilib::Environment::Initialize();
    ocilib::Connection con(OTEXT("db"), OTEXT("usr"), OTEXT("pwd"));

    Statement st(con);
    con.EnableServerOutput(10000, 10, 200);
    st.Prepare(
        "declare "
         "type val_tab is table of number index by binary_integer;"
         "procedure Test( v IN OUT val_tab ) is "
         "begin "
         "for i in 1..v.count loop "
         "  v(i) := i+10; "
         "  DBMS_OUTPUT.PUT_LINE('...v('||i||') = '||v(i)); "
         "end loop; "
         "end Test; "
         "begin "
         " Test(:v);"
         " end;");

    const size_t bufferSize = 10;
    std::vector<Number> numbers(bufferSize);
    for (size_t i = 0; i < bufferSize; i++)
    {
        numbers[i] = Number(std::to_string(i + 1));
    }

    for (const auto& num : numbers)
    {
        std::cout << ": " << "before execution" << num.ToString("99") << std::endl;
    }

    st.Bind(":v", numbers, BindInfo::InOut, BindInfo::AsPlSqlTable);
    st.ExecutePrepared();

    std::string line;
    while (con.GetServerOutput(line))
    {
        std::cout << line << std::endl;
    }

    for(const auto& num : numbers)
    {
        std::cout << ": " << "after execution" << num.ToString("99") << std::endl;
    }

    ocilib::Environment::Cleanup();
}

```

Here is the outout:

```bash
: before execution  1
: before execution  2
: before execution  3
: before execution  4
: before execution  5
: before execution  6
: before execution  7
: before execution  8
: before execution  9
: before execution 10
...v(1) = 11
...v(2) = 12
...v(3) = 13
...v(4) = 14
...v(5) = 15
...v(6) = 16
...v(7) = 17
...v(8) = 18
...v(9) = 19
...v(10) = 20
: after execution 11
: after execution 12
: after execution 13
: after execution 14
: after execution 15
: after execution 16
: after execution 17
: after execution 18
: after execution 19
: after execution 20
```

**Comment by crystalgreen** [comment]
This is frustrating. Your test doesn't work for me, I get the same first part but this last part:
```
: after execution
: after execution
: after execution
: after execution###
: after execution
: after execution
: after execution
: after execution
: after execution
: after execution
```
I tried x86, x64 and various Oracle Instant Client versions (11.2-19.5), different database versions, running within and outside VS, ran on different machines - always the same result (except for those ###). I am using the right branch (develop-4.6.4) and load the newly (release) built ociliba.dll (as shown in the VS output window). I use the latest vs2019 to build with the toolset v142 (you are using an older toolset) and Windows SDK 10.0.
Do you have any idea what I might do wrong?

**Comment by vrogier** [comment]
Bonjour,

I have re-run the test with V2019, toolset v142 in release mode and added version information in the output:

```bash
>>>>> OCILIB BUILD INFORMATION

OCI import mode         : RUNTIME
Charset type            : ANSI

>>>>> VERSIONS INFORMATION

OCILIB major    version : 4
OCILIB minor    version : 6
OCILIB revision version : 4
OCI compile     version : 18
OCI runtime     version : 18
Server major    version : 18
Server minor    version : 3
Server revision version : 0
Connection      version : 1830

>>>>> SERVER VERSION BANNER

Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production
Version 18.3.0.0.0

: before execution  1
: before execution  2
: before execution  3
: before execution  4
: before execution  5
: before execution  6
: before execution  7
: before execution  8
: before execution  9
: before execution 10
...v(1) = 11
...v(2) = 12
...v(3) = 13
...v(4) = 14
...v(5) = 15
...v(6) = 16
...v(7) = 17
...v(8) = 18
...v(9) = 19
...v(10) = 20
: after execution 11
: after execution  2
: after execution  3
: after execution  4
: after execution  5
: after execution  6
: after execution  7
: after execution  8
: after execution  9
: after execution 10
```

Can you re-run your test with added following code and post the output ?

```C++
    cout << otext("\n>>>>> OCILIB BUILD INFORMATION \n\n");

    if (Environment::GetImportMode() == Environment::ImportLinkage)
        cout << otext("OCI import mode         : LINKAGE\n");
    else
        cout << otext("OCI import mode         : RUNTIME\n");

    if (Environment::GetCharset() == Environment::CharsetAnsi)
        cout << otext("Charset type            : ANSI\n");
    else
        cout << otext("Charset type            : WIDE\n");

    cout << otext("\n>>>>> VERSIONS INFORMATION \n\n");
    cout << otext("OCILIB major    version : ") << OCILIB_MAJOR_VERSION << endl;
    cout << otext("OCILIB minor    version : ") << OCILIB_MINOR_VERSION << endl;
    cout << otext("OCILIB revision version : ") << OCILIB_REVISION_VERSION << endl;
    cout << otext("OCI compile     version : ") << Environment::GetCompileMajorVersion() << endl;
    cout << otext("OCI runtime     version : ") << Environment::GetRuntimeMajorVersion() << endl;
    cout << otext("Server major    version : ") << con.GetServerMajorVersion() << endl;
    cout << otext("Server minor    version : ") << con.GetServerMinorVersion() << endl;
    cout << otext("Server revision version : ") << con.GetServerRevisionVersion() << endl;
    cout << otext("Connection      version : ") << static_cast<unsigned int>(con.GetVersion()) << endl;

    ocout << otext("\n>>>>> SERVER VERSION BANNER \n\n");
    ocout << con.GetServerVersion() << oendl << oendl;
```

If you want, you can contact me email and arrange some chat/voice call on the topic :)

Regards,

Vincent

**Comment by vrogier** [comment]
arf, i've just realized that there is a difference in the output between release and debug mode :(
Thus, there might be an issue o the C++ layer on top ofthe OCI API for updating ocilib::Numbers object after the statement execution (as in both mode, debug, release, same DLL is used)

I will investigate that.

**Comment by vrogier** [comment]
Arf, forget my last post. My release folder contained an previous version of OCILIB....

**Comment by vrogier** [comment]
I even rebuilt the C library with the vc142 toolset (as I normally build it with vc141_xp for backward compatibility) in release mode and same result, everything works.

**Comment by crystalgreen** [comment]
I just wrote you a personal email to the address of your github profile.
