### ISSUE TITLE
can ocilib render complex objects?

### ISSUE THREAD

**Issue by GlassyPeou** [vrogier/ocilib#64]
I'm having an issue trying to pull a complex object out of oracle with ocilib. I've provided a mock up of my situation.

Here are SQL objects and tables I'm using:

	CREATE OR REPLACE TYPE BconSys.TestObject AS OBJECT (
		testObjectID	NUMBER(32),
		name			VARCHAR2(32)
	); 
	/
	
	CREATE OR REPLACE TYPE BconSys.TableOfTestObject AS TABLE OF BconSys.TestObject;
	/
	
	CREATE OR REPLACE TYPE BconSys.TestOuterObject AS OBJECT (
		outerObjectID	NUMBER(32),
		outerObjects	BconSys.TableOfTestObject
	); 
	/
	
	CREATE OR REPLACE TYPE BconSys.TableOfTestOuterObject AS TABLE OF BconSys.TestOuterObject;
	/
	
	CREATE OR REPLACE TYPE BconSys.TestOuterObject2 AS OBJECT (
		outerObject2s	BconSys.TableOfTestOuterObject,
		outerObject2ID	NUMBER(32)
	); 
	/
	
	CREATE OR REPLACE TYPE BconSys.TestOuterObject3 AS OBJECT (
		outerObject2	BconSys.TestOuterObject2,
		outerObject3ID	NUMBER(32)
	); 
	/
	
	CREATE TABLE BconSys.OuterObjectTbl (
		column1 BconSys.TestOuterObject3
	)
	NESTED TABLE column1.outerObject2.outerObject2s STORE AS OutObjTbl_items_nt
	(NESTED TABLE outerObjects STORE AS OutObjTbl_item2s_nt);

I insert one row into my table using this statement:
INSERT INTO OuterObjectTbl VALUES( TestOuterObject3( NULL, 1 ) );

Here is my C++ code using ocilib to try and read the data:

	try
	{
		ocilib::Environment::Initialize();
		ocilib::Pool pool(connect, user, pwd, ocilib::Pool::SessionPool, 1, 3, 1);
		ocilib::Connection m_connection = pool.GetConnection();

		ocilib::Statement  m_statement(m_connection);

		m_statement.Prepare(_T("begin select column1 into :1 from OuterObjectTbl; end;"));

		ocilib::Object testObject(ocilib::TypeInfo(m_connection, _T("BCONSYS.TESTOUTEROBJECT3"), ocilib::TypeInfo::Type));

		m_statement.Bind(_T(":1"), testObject, ocilib::BindInfo::Out);

		m_statement.ExecutePrepared();

		int outerObject3ID = testObject.Get<int>(_T("outerObject3ID"));

		ocilib::Environment::Cleanup();
	}
	catch (std::exception &e)
	{
		std::cout << e.what() << std::endl;
	}

An exception is thrown when I try to read the data from "outerObject3ID".
This is the exception: "OCI-22060: argument [2] is an invalid or uninitialized number\n"

I am successful when I'm using less complex objects. Any help would be greatly appreciated.

**Comment by vrogier** [comment]
HI,

I was able to reproduce the issue with provided code.
I'm working on the issue.

Regards,

Vincent

**Comment by vrogier** [comment]
Hi,

Found the issue that is related on how OCILIB computes object attributes offset within object structures which are only accessible using void * buffers.
Although Oracle provides methods for getting/setting object attributes by names, these methods have a nasty bug in Unicode mode that had not been fixed by Oracle for the past 6 years!!
Thus OCILIB has to compute itself the location of a given attribute and has to handle padding and nested sub objects and so on. Which is a bit tricky.

I will commit the fix for it by the weekend after further testing.

You can already test the fix yourself: in src/object.c, line 162:

```C
            OCI_ObjectGetAttrInfo(typinf, i + 1, &size2, &align);

            if (align > typinf->align)
            {
                typinf->align = align;
            }
```

Add another align check before calling OCI_ObjectGetAttrInfo()

```C
           if (align > typinf->align)
	   {
	        typinf->align = align;
	   }

            OCI_ObjectGetAttrInfo(typinf, i + 1, &size2, &align);

            if (align > typinf->align)
            {
                typinf->align = align;
            }
```

I will compute the size of the TestOuterObject2  structure to 32 bytes instead of 30 bytes and you will the correct value for TestOuterObject2::outerObject3ID member :)

Regards,

Vincent

**Comment by GlassyPeou** [comment]
Vincent,

That's great news. I've spent many hours trying to figure this out. Oracle needs to step up and fix some of their issues! Please let me know when you've submitted the final fix. Thanks for your time.

Glassy

**Comment by GlassyPeou** [comment]
Hi,

I’m trying to download the latest ocilib release from this link: https://github.com/vrogier/ocilib/releases/.

Would this be where I get the fix? I want to redownload everything with the adjustment you made to fix that bug.

Thanks

Glassy Peou

**Comment by vrogier** [comment]
Hi,

The fix has been committed in the repo but I haven't made the v4.3.1 release yet.
You can get the source and build ocilib yourself or wait for the release.
I will make the release probably on Wednesday.

Regards,

Vincent

**Comment by GlassyPeou** [comment]
Ok, thank you

Glassy Peou | placesign | Software Engineer
16885 West Bernardo Drive #385, San Diego, CA, 92127
glassy.peou@placesign.com<mailto:glassy.peou@placesign.com> | office: 858.312.7771 x7008 | mobile: 562.277.2833

**Comment by GlassyPeou** [comment]
Hi,

I downloaded the v4.3.1 release and ran my scenario against it and I’m still getting the same issue as before.

I looked at the code around line 162 in object.c file and it looks like this:
162            OCI_ObjectGetAttrInfo(typinf, i + 1, &size2, &align);
163
164            size += size1;
165
166            size = ROUNDUP(size, align);

I don’t see any align checks that you mentioned in a previous email. I was wondering if I downloaded the wrong version perhaps?

Glassy

**Comment by vrogier** [comment]
Hi,

The fix is located in OCI_ObjectGetAttrInfo(), lines 308-311.

I've just re-tested your sample code, on both 32 and 64 bit builds, and I cannot reproduce the issue with v4.3.1.
Are you sure your sample app has loaded the correct version of OCILIB DLL ?

Vincent

**Comment by GlassyPeou** [comment]
You were correct. I was mistakenly using the old dll’s.

Thank you very much
